# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/DK_Praktikum/Hardware/Synthese/synthese.cache/wt [current_project]
set_property parent.project_path C:/DK_Praktikum/Hardware/Synthese/synthese.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/DK_Praktikum/Hardware/Synthese/synthese.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/DK_Praktikum/Hardware/Synthese/synthese.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_vhdl -library xil_defaultlib {
  C:/DK_Praktikum/Hardware/Prozessor/DF_Serial_in_v1_0.vhd
  C:/DK_Praktikum/Hardware/Prozessor/DF_Wishbone_Interface.vhd
  C:/DK_Praktikum/Hardware/Prozessor/DF_Serial_out_v1_0.vhd
  C:/DK_Praktikum/Hardware/Prozessor/Serial_Wishbone_Interface.vhd
  C:/DK_Praktikum/Hardware/Prozessor/wb_arbiter.vhd
  C:/DK_Praktikum/Hardware/Prozessor/mult.vhd
  C:/DK_Praktikum/Hardware/Prozessor/div.vhd
  C:/DK_Praktikum/Hardware/Prozessor/bsr2_processor_core.vhd
  C:/DK_Praktikum/Hardware/Prozessor/bsr2_processor.vhd
  C:/DK_Praktikum/Hardware/DMA_Controller/DMA_Kanal.vhd
  C:/DK_Praktikum/Hardware/DMA_Controller/DMA_Kontroller.vhd
  C:/DK_Praktikum/Hardware/Speicher/bsr2_rom.vhd
  C:/DK_Praktikum/Hardware/Speicher/bsr2_ram.vhd
  C:/DK_Praktikum/Hardware/GPIO/GPIO.vhd
  C:/DK_Praktikum/Hardware/UART/Serieller_Empfaenger.vhd
  C:/DK_Praktikum/Hardware/UART/Serieller_Sender.vhd
  C:/DK_Praktikum/Hardware/UART/UART.vhd
  C:/DK_Praktikum/Hardware/Timer/Timer.vhd
  C:/DK_Praktikum/Hardware/Beispielrechner_System.vhd
}
add_files C:/DK_Praktikum/Hardware/Synthese/synthese.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/DK_Praktikum/Hardware/Synthese/synthese.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/DK_Praktikum/Hardware/Synthese/synthese.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/DK_Praktikum/Hardware/Synthese/synthese.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/DK_Praktikum/Hardware/Synthese/synthese.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/DK_Praktikum/Hardware/Beispielrechner_System.xdc
set_property used_in_implementation false [get_files C:/DK_Praktikum/Hardware/Beispielrechner_System.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
